name: Testando CI/CD com Github Actions

on:
    push:
        branches:
            - main

jobs:
    primeiro_test_sozinho:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do projeto
              uses: actions/checkout@v4

            - name: Listar os diretórios
              run: ls -la

            - name: Exibindo o diretório atual
              run: echo "${{github.action_path}}"

            - name: Exibindo conteudo da pasta
              run: |
                  cd .github/workflows
                  ls -ls
                  cd ./

            - name: Log de contexto
              run: |
                  echo "Repo: ${{github.repository}}"
                  echo "Branch: ${{github.ref_name}}"
                  echo "Commit: ${{github.sha}}"
