name: Aplicando CI/CD com codigo TS

on:
    push:
        branches:
            - dev

jobs:
    ci_dev:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do projeto
              uses: actions/checkout@v4

            - name: Log de contexto
              run: |
                  echo "Repository: ${{github.repository}}"
                  echo "Branch: ${{github.ref_name}}"
                  echo "Commit: ${{github.sha}}"

            - name: Instalando dependÃªncias
              run: npm install

            - name: Rodando testes
              run: npm run test

            - name: Build
              run: npm run build

            - name: Iniciar
              run: npm run start
