name: Teste manual com workflow_dispatch

on:
    # S√ì RODA MANUALMENTE
    workflow_dispatch:
        # CRIA UM CAMPO NO FORMUL√ÅRIO
        inputs:
            environment:
                description: "Ambiente de execu√ß√£o"
                required: true
                default: "staging"
                type: choice
                options:
                    - staging
                    - production

# RUNNER PADR√ÉO
jobs:
    manual_job:
        runs-on: ubuntu-latest
        steps:
            - name: Mostrar contexto b√°sico
              run: |
                  echo "Evento: ${{github.event_name}}"
                  echo "Usu√°rio: ${{github.actor}}"
                  echo "Ambiente escolhido: ${{github.event.inputs.environment}}"

            - name: Executar l√≥gica condicional
              run: |
                  if [ "${{github.event.inputs.environment}}" = "production"]; then 
                    echo "üö® Produ√ß√£o selecionada!"
                  else 
                    echo "üß™ Ambiente de testes (staging)"
                  fi
